# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compound_bow_test_software.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BowAnalyzer(object):
    def setupUi(self, BowAnalyzer):
        BowAnalyzer.setObjectName("BowAnalyzer")
        BowAnalyzer.resize(1360, 700)
        self.centralwidget = QtWidgets.QWidget(BowAnalyzer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 541, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.cam1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.cam1.setContentsMargins(0, 0, 0, 0)
        self.cam1.setObjectName("cam1")
        self.cam1_lbl = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.cam1_lbl.setAutoFillBackground(False)
        self.cam1_lbl.setText("")
        self.cam1_lbl.setObjectName("cam1_lbl")
        self.cam1.addWidget(self.cam1_lbl)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(840, 20, 511, 431))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.cam2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.cam2.setContentsMargins(0, 0, 0, 0)
        self.cam2.setObjectName("cam2")
        self.cam2_lbl = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.cam2_lbl.setText("")
        self.cam2_lbl.setObjectName("cam2_lbl")
        self.cam2.addWidget(self.cam2_lbl)
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setGeometry(QtCore.QRect(640, 180, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.stop_btn.setFont(font)
        self.stop_btn.setObjectName("stop_btn")
        self.start_plot = QtWidgets.QPushButton(self.centralwidget)
        self.start_plot.setGeometry(QtCore.QRect(630, 540, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.start_plot.setFont(font)
        self.start_plot.setObjectName("start_plot")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 470, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(980, 480, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        BowAnalyzer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BowAnalyzer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1360, 21))
        self.menubar.setObjectName("menubar")
        BowAnalyzer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BowAnalyzer)
        self.statusbar.setObjectName("statusbar")
        BowAnalyzer.setStatusBar(self.statusbar)

        self.retranslateUi(BowAnalyzer)
        QtCore.QMetaObject.connectSlotsByName(BowAnalyzer)

    def retranslateUi(self, BowAnalyzer):
        _translate = QtCore.QCoreApplication.translate
        BowAnalyzer.setWindowTitle(_translate("BowAnalyzer", "Bow Analyzer"))
        self.stop_btn.setText(_translate("BowAnalyzer", "Stop"))
        self.start_plot.setText(_translate("BowAnalyzer", "Start Plotting"))
        self.label.setText(_translate("BowAnalyzer", "CAM-1"))
        self.label_2.setText(_translate("BowAnalyzer", "CAM-2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BowAnalyzer = QtWidgets.QMainWindow()
    ui = Ui_BowAnalyzer()
    ui.setupUi(BowAnalyzer)
    BowAnalyzer.show()
    sys.exit(app.exec_())
