# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotter_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotWindow(object):
    def setupUi(self, PlotWindow):
        PlotWindow.setObjectName("PlotWindow")
        PlotWindow.resize(903, 704)
        self.centralwidget = QtWidgets.QWidget(PlotWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.plot_view = PlotWidget(self.centralwidget)
        self.plot_view.setMinimumSize(QtCore.QSize(781, 0))
        self.plot_view.setMaximumSize(QtCore.QSize(20000, 20000))
        self.plot_view.setObjectName("plot_view")
        self.verticalLayout.addWidget(self.plot_view)
        self.stoppltbtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.stoppltbtn.setFont(font)
        self.stoppltbtn.setObjectName("stoppltbtn")
        self.verticalLayout.addWidget(self.stoppltbtn)
        self.savebtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.savebtn.setFont(font)
        self.savebtn.setObjectName("savebtn")
        self.verticalLayout.addWidget(self.savebtn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        PlotWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PlotWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 903, 21))
        self.menubar.setObjectName("menubar")
        PlotWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PlotWindow)
        self.statusbar.setObjectName("statusbar")
        PlotWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PlotWindow)
        QtCore.QMetaObject.connectSlotsByName(PlotWindow)

    def retranslateUi(self, PlotWindow):
        _translate = QtCore.QCoreApplication.translate
        PlotWindow.setWindowTitle(_translate("PlotWindow", "MainWindow"))
        self.stoppltbtn.setText(_translate("PlotWindow", "Stop"))
        self.savebtn.setText(_translate("PlotWindow", "Save Results"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlotWindow = QtWidgets.QMainWindow()
    ui = Ui_PlotWindow()
    ui.setupUi(PlotWindow)
    PlotWindow.show()
    sys.exit(app.exec_())
