# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Nameswindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime
from compound_bow_test_software import Ui_BowAnalyzer

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(558, 355)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Itemlbl = QtWidgets.QLabel(self.centralwidget)
        self.Itemlbl.setGeometry(QtCore.QRect(130, 120, 121, 31))
        self.Itemlbl.setObjectName("Itemlbl")
        self.datelbl = QtWidgets.QLabel(self.centralwidget)
        self.datelbl.setGeometry(QtCore.QRect(130, 170, 121, 31))
        self.datelbl.setObjectName("datelbl")
        self.txtbox = QtWidgets.QLineEdit(self.centralwidget)
        self.txtbox.setGeometry(QtCore.QRect(260, 129, 181, 21))
        self.txtbox.setObjectName("txtbox")
        self.dtbox = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dtbox.setGeometry(QtCore.QRect(260, 180, 194, 22))
        self.dtbox.setObjectName("dtbox")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(190, 250, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.submit.clicked.connect(self.submit_btn)
        self.submit.clicked.connect(self.open_new_window)
        self.submit.clicked.connect(MainWindow.close)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Itemlbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Item Code:</span></p></body></html>"))
        self.datelbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Date:</span></p></body></html>"))
        self.submit.setText(_translate("MainWindow", "Submit"))

    def submit_btn(self):
        filename = self.txtbox.text()
        return str(filename)

    def get_item(self):
        itemcode = self.txtbox.text()
        print('Getitem', itemcode)
        return itemcode

    def open_new_window(self):
        self.cam_vid_window = QtWidgets.QMainWindow()
        self.ui = Ui_BowAnalyzer()
        self.ui.setupUi(self.cam_vid_window)
        self.cam_vid_window.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    print(ui.submit_btn())
    sys.exit(app.exec_())
