# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Nameswindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StartupWindow(object):
    def setupUi(self, StartupWindow):
        StartupWindow.setObjectName("StartupWindow")
        StartupWindow.resize(454, 137)
        self.centralwidget = QtWidgets.QWidget(StartupWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 421, 101))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.Itemlbl = QtWidgets.QLabel(self.widget)
        self.Itemlbl.setObjectName("Itemlbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Itemlbl)
        self.item_code = QtWidgets.QLineEdit(self.widget)
        self.item_code.setObjectName("item_code")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.item_code)
        self.datelbl = QtWidgets.QLabel(self.widget)
        self.datelbl.setObjectName("datelbl")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.datelbl)
        self.submit_btn = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.submit_btn.setFont(font)
        self.submit_btn.setObjectName("submit_btn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.submit_btn)
        self.cam_no = QtWidgets.QLineEdit(self.widget)
        self.cam_no.setObjectName("cam_no")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cam_no)
        StartupWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(StartupWindow)
        QtCore.QMetaObject.connectSlotsByName(StartupWindow)

    def retranslateUi(self, StartupWindow):
        _translate = QtCore.QCoreApplication.translate
        StartupWindow.setWindowTitle(_translate("StartupWindow", "MainWindow"))
        self.Itemlbl.setText(_translate("StartupWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Item Code:</span></p></body></html>"))
        self.datelbl.setText(_translate("StartupWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">CAM No.:</span></p></body></html>"))
        self.submit_btn.setText(_translate("StartupWindow", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StartupWindow = QtWidgets.QMainWindow()
    ui = Ui_StartupWindow()
    ui.setupUi(StartupWindow)
    StartupWindow.show()
    sys.exit(app.exec_())
